import type { ChildGrade, Feature, SchoolType, Suburb } from "@/lib/affordable-schools/types";

type SchoolSeed = {
  name: string;
  suburbSlug: string;
  schoolType: SchoolType;
  annualFeeMin: number;
  annualFeeMax: number;
  registrationFee: number;
  depositFee: number;
  aftercareAvailable: boolean;
  transportAvailable: boolean;
  swimmingAvailable: boolean;
  sports: string[];
  facilities: string[];
  mustHaveFeatures: Feature[];
  niceToHaveFeatures: Feature[];
  curriculum: string;
  religiousAffiliation?: string;
  classSizeEstimate: number;
  latitudeOffset: number;
  longitudeOffset: number;
  distanceFromSuburbCenterKm: number;
};

export const MIDRAND_LAST_UPDATED_AT = "2026-03-17T12:00:00.000Z";

export const midrandSuburbs: Suburb[] = [
  { id: "suburb-noordwyk", name: "Noordwyk", slug: "noordwyk", medianBudgetBand: "R4 500-R8 000 monthly", pitch: "Popular with practical family budgets and quick N1 access.", latitude: -25.966, longitude: 28.126 },
  { id: "suburb-halfway-gardens", name: "Halfway Gardens", slug: "halfway-gardens", medianBudgetBand: "R5 500-R9 500 monthly", pitch: "Central Midrand location with balanced commute options.", latitude: -25.986, longitude: 28.123 },
  { id: "suburb-vorna-valley", name: "Vorna Valley", slug: "vorna-valley", medianBudgetBand: "R5 000-R8 500 monthly", pitch: "Convenient for families prioritising practical routes and aftercare.", latitude: -26.008, longitude: 28.116 },
  { id: "suburb-buccleuch", name: "Buccleuch", slug: "buccleuch", medianBudgetBand: "R5 000-R8 500 monthly", pitch: "Useful for households balancing Midrand and Sandton work patterns.", latitude: -26.058, longitude: 28.099 },
  { id: "suburb-carlswald", name: "Carlswald", slug: "carlswald", medianBudgetBand: "R6 500-R11 000 monthly", pitch: "A family-oriented pocket with many private-school options nearby.", latitude: -25.946, longitude: 28.139 },
  { id: "suburb-kyalami", name: "Kyalami", slug: "kyalami", medianBudgetBand: "R8 500-R13 000 monthly", pitch: "Good for families who value facilities, sport, and more space.", latitude: -25.964, longitude: 28.071 },
  { id: "suburb-barbeque-downs", name: "Barbeque Downs", slug: "barbeque-downs", medianBudgetBand: "R6 000-R9 500 monthly", pitch: "Compact suburb that suits practical commuting and mixed school choices.", latitude: -26.023, longitude: 28.094 },
  { id: "suburb-waterfall", name: "Waterfall", slug: "waterfall", medianBudgetBand: "R8 000-R14 000 monthly", pitch: "Newer family nodes with stronger premium-school spillover.", latitude: -26.018, longitude: 28.103 },
  { id: "suburb-blue-hills", name: "Blue Hills", slug: "blue-hills", medianBudgetBand: "R5 500-R9 000 monthly", pitch: "Useful for families seeking more value while staying in the Midrand orbit.", latitude: -25.928, longitude: 28.101 },
  { id: "suburb-glen-austin", name: "Glen Austin", slug: "glen-austin", medianBudgetBand: "R6 500-R10 500 monthly", pitch: "A quieter Midrand pocket with a mix of established and boutique schools.", latitude: -25.958, longitude: 28.152 },
];

const gradeR: ChildGrade = "Grade R";
const grade7: ChildGrade = "Grade 7";

export const schoolCoverage = {
  gradesFrom: gradeR,
  gradesTo: grade7,
};

export const midrandSchoolSeeds: SchoolSeed[] = [
  { name: "Midrand English Medium Primary School", suburbSlug: "noordwyk", schoolType: "public", annualFeeMin: 18000, annualFeeMax: 26000, registrationFee: 1200, depositFee: 2200, aftercareAvailable: true, transportAvailable: false, swimmingAvailable: false, sports: ["Soccer", "Netball", "Cricket"], facilities: ["Library", "Hall", "Playground"], mustHaveFeatures: ["Aftercare", "Soccer", "Library"], niceToHaveFeatures: ["Meal option", "Extra murals"], curriculum: "CAPS", classSizeEstimate: 31, latitudeOffset: 0.003, longitudeOffset: -0.004, distanceFromSuburbCenterKm: 2.3 },
  { name: "Midrand Christian College", suburbSlug: "noordwyk", schoolType: "private_mid_tier", annualFeeMin: 62000, annualFeeMax: 89000, registrationFee: 6500, depositFee: 9500, aftercareAvailable: true, transportAvailable: true, swimmingAvailable: true, sports: ["Soccer", "Rugby", "Netball", "Music"], facilities: ["Library", "Swimming pool", "Computer lab"], mustHaveFeatures: ["Aftercare", "Transport", "Music"], niceToHaveFeatures: ["Modern classrooms", "Holiday care"], curriculum: "CAPS with Christian enrichment", religiousAffiliation: "Christian", classSizeEstimate: 24, latitudeOffset: -0.002, longitudeOffset: 0.003, distanceFromSuburbCenterKm: 3.1 },
  { name: "Midrand Montessori Preschool and Primary", suburbSlug: "noordwyk", schoolType: "private_mid_tier", annualFeeMin: 58000, annualFeeMax: 81000, registrationFee: 5500, depositFee: 8200, aftercareAvailable: true, transportAvailable: true, swimmingAvailable: false, sports: ["Soccer", "Music"], facilities: ["Garden classrooms", "Library", "Art room"], mustHaveFeatures: ["Small classes", "Aftercare"], niceToHaveFeatures: ["Modern classrooms", "Holiday care"], curriculum: "Montessori", classSizeEstimate: 18, latitudeOffset: 0.004, longitudeOffset: 0.001, distanceFromSuburbCenterKm: 1.8 },
  { name: "Halfway House Primary School", suburbSlug: "halfway-gardens", schoolType: "public", annualFeeMin: 16000, annualFeeMax: 24000, registrationFee: 1000, depositFee: 1800, aftercareAvailable: true, transportAvailable: false, swimmingAvailable: false, sports: ["Soccer", "Netball", "Cricket"], facilities: ["Library", "Hall", "Computer lab"], mustHaveFeatures: ["Aftercare", "Soccer"], niceToHaveFeatures: ["Library", "Meal option"], curriculum: "CAPS", classSizeEstimate: 33, latitudeOffset: 0.001, longitudeOffset: -0.002, distanceFromSuburbCenterKm: 2.1 },
  { name: "Laerskool Halfway House", suburbSlug: "halfway-gardens", schoolType: "public", annualFeeMin: 15000, annualFeeMax: 22500, registrationFee: 950, depositFee: 1650, aftercareAvailable: true, transportAvailable: false, swimmingAvailable: false, sports: ["Rugby", "Cricket", "Netball"], facilities: ["Library", "Sports fields", "Hall"], mustHaveFeatures: ["Aftercare", "Rugby", "Cricket"], niceToHaveFeatures: ["Meal option", "Extra murals"], curriculum: "CAPS", classSizeEstimate: 32, latitudeOffset: -0.003, longitudeOffset: -0.004, distanceFromSuburbCenterKm: 2.8 },
  { name: "Christ Church Preparatory School and College", suburbSlug: "halfway-gardens", schoolType: "private_mid_tier", annualFeeMin: 70000, annualFeeMax: 96000, registrationFee: 7000, depositFee: 10500, aftercareAvailable: true, transportAvailable: true, swimmingAvailable: true, sports: ["Soccer", "Netball", "Music", "Swimming"], facilities: ["Library", "Swimming pool", "STEM lab"], mustHaveFeatures: ["Aftercare", "Transport", "Swimming"], niceToHaveFeatures: ["Coding/Robotics", "Modern classrooms"], curriculum: "CAPS", religiousAffiliation: "Christian", classSizeEstimate: 23, latitudeOffset: 0.004, longitudeOffset: 0.002, distanceFromSuburbCenterKm: 3.6 },
  { name: "Cedarwood School", suburbSlug: "vorna-valley", schoolType: "private_mid_tier", annualFeeMin: 52000, annualFeeMax: 76000, registrationFee: 4800, depositFee: 7600, aftercareAvailable: true, transportAvailable: true, swimmingAvailable: false, sports: ["Soccer", "Netball", "Music"], facilities: ["Library", "Therapy room", "Computer lab"], mustHaveFeatures: ["Aftercare", "Transport", "Small classes"], niceToHaveFeatures: ["Modern classrooms", "Holiday care"], curriculum: "Learner support CAPS", classSizeEstimate: 16, latitudeOffset: 0.002, longitudeOffset: 0.003, distanceFromSuburbCenterKm: 2.9 },
  { name: "Modern Montessori International", suburbSlug: "vorna-valley", schoolType: "private_mid_tier", annualFeeMin: 61000, annualFeeMax: 86000, registrationFee: 6000, depositFee: 8400, aftercareAvailable: true, transportAvailable: false, swimmingAvailable: false, sports: ["Music", "Soccer"], facilities: ["Art studio", "Garden classrooms", "Library"], mustHaveFeatures: ["Small classes", "Aftercare"], niceToHaveFeatures: ["Modern classrooms", "Library"], curriculum: "Montessori", classSizeEstimate: 17, latitudeOffset: -0.002, longitudeOffset: 0.002, distanceFromSuburbCenterKm: 2.6 },
  { name: "Curro Midrand Sagewood", suburbSlug: "vorna-valley", schoolType: "private_mid_tier", annualFeeMin: 78000, annualFeeMax: 112000, registrationFee: 7500, depositFee: 12000, aftercareAvailable: true, transportAvailable: true, swimmingAvailable: true, sports: ["Swimming", "Soccer", "Cricket", "Netball"], facilities: ["Swimming pool", "STEM lab", "Library"], mustHaveFeatures: ["Aftercare", "Transport", "Swimming"], niceToHaveFeatures: ["Coding/Robotics", "Modern classrooms"], curriculum: "CAPS", classSizeEstimate: 24, latitudeOffset: 0.004, longitudeOffset: -0.003, distanceFromSuburbCenterKm: 4.7 },
  { name: "SPARK Midrand", suburbSlug: "buccleuch", schoolType: "private_low_fee", annualFeeMin: 32000, annualFeeMax: 46000, registrationFee: 2500, depositFee: 3600, aftercareAvailable: true, transportAvailable: false, swimmingAvailable: false, sports: ["Soccer", "Netball"], facilities: ["Modern classrooms", "Computer lab"], mustHaveFeatures: ["Aftercare", "Coding/Robotics"], niceToHaveFeatures: ["Modern classrooms", "Sibling discount"], curriculum: "CAPS", classSizeEstimate: 28, latitudeOffset: 0.003, longitudeOffset: 0.003, distanceFromSuburbCenterKm: 4.2 },
  { name: "Midrand Muslim School", suburbSlug: "buccleuch", schoolType: "private_low_fee", annualFeeMin: 36000, annualFeeMax: 52000, registrationFee: 2800, depositFee: 4000, aftercareAvailable: true, transportAvailable: true, swimmingAvailable: false, sports: ["Soccer", "Netball", "Cricket"], facilities: ["Library", "Prayer space", "Computer lab"], mustHaveFeatures: ["Transport", "Religious alignment"], niceToHaveFeatures: ["Meal option", "Extra murals"], curriculum: "CAPS", religiousAffiliation: "Muslim", classSizeEstimate: 27, latitudeOffset: -0.002, longitudeOffset: -0.001, distanceFromSuburbCenterKm: 4.8 },
  { name: "Midrand Primary and High School", suburbSlug: "buccleuch", schoolType: "public", annualFeeMin: 14000, annualFeeMax: 21000, registrationFee: 950, depositFee: 1500, aftercareAvailable: true, transportAvailable: false, swimmingAvailable: false, sports: ["Soccer", "Netball"], facilities: ["Library", "Hall", "Computer lab"], mustHaveFeatures: ["Aftercare", "Soccer"], niceToHaveFeatures: ["Meal option", "Library"], curriculum: "CAPS", classSizeEstimate: 34, latitudeOffset: 0.001, longitudeOffset: -0.003, distanceFromSuburbCenterKm: 5.4 },
  { name: "Beaulieu Preparatory School", suburbSlug: "carlswald", schoolType: "private_premium", annualFeeMin: 128000, annualFeeMax: 162000, registrationFee: 12000, depositFee: 18000, aftercareAvailable: true, transportAvailable: true, swimmingAvailable: true, sports: ["Swimming", "Rugby", "Cricket", "Music"], facilities: ["Equestrian access", "Swimming pool", "Library"], mustHaveFeatures: ["Transport", "Swimming", "Small classes"], niceToHaveFeatures: ["Modern classrooms", "Holiday care"], curriculum: "CAPS", classSizeEstimate: 19, latitudeOffset: 0.003, longitudeOffset: 0.004, distanceFromSuburbCenterKm: 3.2 },
  { name: "Maria Montessori House of Children", suburbSlug: "carlswald", schoolType: "private_mid_tier", annualFeeMin: 64000, annualFeeMax: 92000, registrationFee: 6200, depositFee: 9000, aftercareAvailable: true, transportAvailable: false, swimmingAvailable: false, sports: ["Music", "Soccer"], facilities: ["Garden classrooms", "Library", "Art room"], mustHaveFeatures: ["Small classes", "Aftercare"], niceToHaveFeatures: ["Modern classrooms", "Library"], curriculum: "Montessori", classSizeEstimate: 16, latitudeOffset: -0.003, longitudeOffset: 0.001, distanceFromSuburbCenterKm: 2.5 },
  { name: "Summerhill College", suburbSlug: "carlswald", schoolType: "private_mid_tier", annualFeeMin: 76000, annualFeeMax: 108000, registrationFee: 7800, depositFee: 12200, aftercareAvailable: true, transportAvailable: true, swimmingAvailable: true, sports: ["Swimming", "Soccer", "Cricket", "Netball"], facilities: ["Swimming pool", "Library", "Computer lab"], mustHaveFeatures: ["Aftercare", "Transport", "Swimming"], niceToHaveFeatures: ["Coding/Robotics", "Modern classrooms"], curriculum: "CAPS", classSizeEstimate: 24, latitudeOffset: 0.002, longitudeOffset: -0.002, distanceFromSuburbCenterKm: 3.9 },
  { name: "Kyalami Preparatory School", suburbSlug: "kyalami", schoolType: "private_premium", annualFeeMin: 136000, annualFeeMax: 170000, registrationFee: 13000, depositFee: 19000, aftercareAvailable: true, transportAvailable: true, swimmingAvailable: true, sports: ["Swimming", "Rugby", "Cricket", "Netball"], facilities: ["Swimming pool", "Library", "Sports fields"], mustHaveFeatures: ["Swimming", "Transport", "Small classes"], niceToHaveFeatures: ["Holiday care", "Modern classrooms"], curriculum: "CAPS", classSizeEstimate: 18, latitudeOffset: 0.003, longitudeOffset: -0.003, distanceFromSuburbCenterKm: 3.8 },
  { name: "Jubilate Primary School", suburbSlug: "kyalami", schoolType: "private_low_fee", annualFeeMin: 30000, annualFeeMax: 44000, registrationFee: 2400, depositFee: 3500, aftercareAvailable: true, transportAvailable: true, swimmingAvailable: false, sports: ["Soccer", "Netball", "Music"], facilities: ["Library", "Hall", "Computer lab"], mustHaveFeatures: ["Aftercare", "Transport", "Music"], niceToHaveFeatures: ["Meal option", "Holiday care"], curriculum: "CAPS", religiousAffiliation: "Christian", classSizeEstimate: 26, latitudeOffset: -0.004, longitudeOffset: 0.002, distanceFromSuburbCenterKm: 4.4 },
  { name: "Midrand Christian Academy", suburbSlug: "kyalami", schoolType: "private_low_fee", annualFeeMin: 34000, annualFeeMax: 49000, registrationFee: 2600, depositFee: 3800, aftercareAvailable: true, transportAvailable: true, swimmingAvailable: false, sports: ["Soccer", "Netball", "Music"], facilities: ["Library", "Assembly hall", "Computer lab"], mustHaveFeatures: ["Aftercare", "Transport", "Religious alignment"], niceToHaveFeatures: ["Meal option", "Sibling discount"], curriculum: "CAPS", religiousAffiliation: "Christian", classSizeEstimate: 28, latitudeOffset: 0.001, longitudeOffset: 0.004, distanceFromSuburbCenterKm: 4.9 },
  { name: "Noor Training Centre", suburbSlug: "barbeque-downs", schoolType: "private_low_fee", annualFeeMin: 26000, annualFeeMax: 39000, registrationFee: 2100, depositFee: 3000, aftercareAvailable: true, transportAvailable: true, swimmingAvailable: false, sports: ["Soccer", "Netball"], facilities: ["Library", "Prayer space", "Computer lab"], mustHaveFeatures: ["Transport", "Religious alignment"], niceToHaveFeatures: ["Meal option", "Holiday care"], curriculum: "CAPS", religiousAffiliation: "Muslim", classSizeEstimate: 27, latitudeOffset: 0.002, longitudeOffset: -0.004, distanceFromSuburbCenterKm: 3.4 },
  { name: "Bonwelong Primary School", suburbSlug: "barbeque-downs", schoolType: "public", annualFeeMin: 12000, annualFeeMax: 19500, registrationFee: 900, depositFee: 1400, aftercareAvailable: false, transportAvailable: false, swimmingAvailable: false, sports: ["Soccer", "Netball"], facilities: ["Hall", "Playground"], mustHaveFeatures: ["Soccer"], niceToHaveFeatures: ["Meal option", "Extra murals"], curriculum: "CAPS", classSizeEstimate: 36, latitudeOffset: -0.003, longitudeOffset: 0.001, distanceFromSuburbCenterKm: 3.9 },
  { name: "Eqinisweni Primary School", suburbSlug: "waterfall", schoolType: "public", annualFeeMin: 12500, annualFeeMax: 20000, registrationFee: 850, depositFee: 1350, aftercareAvailable: false, transportAvailable: false, swimmingAvailable: false, sports: ["Soccer", "Netball"], facilities: ["Hall", "Playground", "Computer lab"], mustHaveFeatures: ["Soccer"], niceToHaveFeatures: ["Library", "Meal option"], curriculum: "CAPS", classSizeEstimate: 35, latitudeOffset: -0.001, longitudeOffset: -0.002, distanceFromSuburbCenterKm: 5.1 },
  { name: "Reddam House Waterfall", suburbSlug: "waterfall", schoolType: "private_premium", annualFeeMin: 142000, annualFeeMax: 178000, registrationFee: 13500, depositFee: 21000, aftercareAvailable: true, transportAvailable: true, swimmingAvailable: true, sports: ["Swimming", "Rugby", "Cricket", "Music"], facilities: ["Performing arts centre", "Swimming pool", "Library"], mustHaveFeatures: ["Transport", "Swimming", "Music"], niceToHaveFeatures: ["Coding/Robotics", "Modern classrooms"], curriculum: "IEB-aligned primary", classSizeEstimate: 20, latitudeOffset: 0.004, longitudeOffset: -0.001, distanceFromSuburbCenterKm: 4.2 },
  { name: "Waterfall Montessori", suburbSlug: "waterfall", schoolType: "private_mid_tier", annualFeeMin: 68000, annualFeeMax: 93000, registrationFee: 6500, depositFee: 9800, aftercareAvailable: true, transportAvailable: false, swimmingAvailable: false, sports: ["Music", "Soccer"], facilities: ["Garden classrooms", "Art room", "Library"], mustHaveFeatures: ["Small classes", "Aftercare"], niceToHaveFeatures: ["Modern classrooms", "Holiday care"], curriculum: "Montessori", classSizeEstimate: 17, latitudeOffset: 0.002, longitudeOffset: 0.003, distanceFromSuburbCenterKm: 3.6 },
  { name: "Reddford House Blue Hills", suburbSlug: "blue-hills", schoolType: "private_premium", annualFeeMin: 138000, annualFeeMax: 172000, registrationFee: 13200, depositFee: 19600, aftercareAvailable: true, transportAvailable: true, swimmingAvailable: true, sports: ["Swimming", "Soccer", "Cricket", "Music"], facilities: ["Swimming pool", "Library", "STEM lab"], mustHaveFeatures: ["Transport", "Swimming", "Music"], niceToHaveFeatures: ["Coding/Robotics", "Modern classrooms"], curriculum: "IEB-aligned primary", classSizeEstimate: 21, latitudeOffset: 0.002, longitudeOffset: -0.002, distanceFromSuburbCenterKm: 4.8 },
  { name: "Blue Hills College", suburbSlug: "blue-hills", schoolType: "private_low_fee", annualFeeMin: 28000, annualFeeMax: 42000, registrationFee: 2200, depositFee: 3200, aftercareAvailable: true, transportAvailable: true, swimmingAvailable: false, sports: ["Soccer", "Netball", "Cricket"], facilities: ["Library", "Hall", "Computer lab"], mustHaveFeatures: ["Aftercare", "Transport"], niceToHaveFeatures: ["Meal option", "Sibling discount"], curriculum: "CAPS", classSizeEstimate: 29, latitudeOffset: -0.003, longitudeOffset: 0.003, distanceFromSuburbCenterKm: 3.3 },
  { name: "Nizamiye School", suburbSlug: "blue-hills", schoolType: "private_mid_tier", annualFeeMin: 54000, annualFeeMax: 76000, registrationFee: 5200, depositFee: 7600, aftercareAvailable: true, transportAvailable: true, swimmingAvailable: true, sports: ["Swimming", "Soccer", "Music"], facilities: ["Library", "Prayer space", "Science lab"], mustHaveFeatures: ["Transport", "Swimming", "Religious alignment"], niceToHaveFeatures: ["Modern classrooms", "Meal option"], curriculum: "CAPS", religiousAffiliation: "Muslim", classSizeEstimate: 23, latitudeOffset: 0.004, longitudeOffset: 0.002, distanceFromSuburbCenterKm: 4.1 },
  { name: "Phumulani Primary School", suburbSlug: "glen-austin", schoolType: "public", annualFeeMin: 12000, annualFeeMax: 19000, registrationFee: 850, depositFee: 1350, aftercareAvailable: false, transportAvailable: false, swimmingAvailable: false, sports: ["Soccer", "Netball"], facilities: ["Hall", "Playground"], mustHaveFeatures: ["Soccer"], niceToHaveFeatures: ["Meal option", "Extra murals"], curriculum: "CAPS", classSizeEstimate: 37, latitudeOffset: 0.002, longitudeOffset: -0.004, distanceFromSuburbCenterKm: 3.8 },
  { name: "Glen Austin Primary School", suburbSlug: "glen-austin", schoolType: "public", annualFeeMin: 13500, annualFeeMax: 20500, registrationFee: 900, depositFee: 1450, aftercareAvailable: true, transportAvailable: false, swimmingAvailable: false, sports: ["Soccer", "Cricket", "Netball"], facilities: ["Library", "Hall", "Playground"], mustHaveFeatures: ["Aftercare", "Cricket"], niceToHaveFeatures: ["Library", "Extra murals"], curriculum: "CAPS", classSizeEstimate: 33, latitudeOffset: -0.002, longitudeOffset: 0.001, distanceFromSuburbCenterKm: 2.7 },
  { name: "Noordwyk Primary School", suburbSlug: "glen-austin", schoolType: "public", annualFeeMin: 14500, annualFeeMax: 21500, registrationFee: 950, depositFee: 1600, aftercareAvailable: true, transportAvailable: false, swimmingAvailable: false, sports: ["Soccer", "Netball", "Music"], facilities: ["Library", "Computer lab", "Playground"], mustHaveFeatures: ["Aftercare", "Music"], niceToHaveFeatures: ["Meal option", "Library"], curriculum: "CAPS", classSizeEstimate: 31, latitudeOffset: 0.003, longitudeOffset: 0.002, distanceFromSuburbCenterKm: 4.3 },
];
